### ISSUE TITLE
Upload to other cloud drives or file sharing sites. Such as: Google, mega (https://mega.io/)

### ISSUE THREAD

**Issue by My12123** [1439707509/pygui#3]
上传到其他云驱动器或文件共享网站。
Google, mega ([https://mega.io/](https://mega.io/))

**Comment by 1439707509** [comment]
> 上传到其他云驱动器或文件共享网站。 Google, mega ( https://mega.io/ )

那天不会再频繁更新，再上传到mega，要不你上传了，发联接给我

**Comment by 1439707509** [comment]
> 上传到其他云驱动器或文件共享网站。 Google, mega (https://mega.io/)

刚刚又加上 
https://github.com/adbar/py3langid

我又要重新打包了，我不可能天天维护这个，等那天不再频繁更新再说
