### ISSUE TITLE
Can you translate into many languages?

### ISSUE THREAD

**Issue by My12123** [1439707509/pygui#4]
Can you translate into many languages?
languages These include:
Englishman
Spanish
Arabian
Russian
French
Chinese). I am interested in Russian. If yes, what?

你能翻译成多种语言吗?
语言包括:
英国人
西班牙语
阿拉伯
俄语
法语
中文）。 我对俄语感兴趣。 如果是的话，什么？

**Comment by 1439707509** [comment]
> 你能翻译成多种语言吗？ 语言 这些包括： Englishman Spanish Arabian Russian French Chinese）。我对俄语很感兴趣。如果是，什么？
> 
> 你能翻译成多种语言吗? 语言包例如: 英国人 西班牙语 阿拉伯 俄语 法语 中文)。我对俄语感兴趣。如果是的话，是什么？

每次原版有啥变化，我也要跟着改，除非原版不再有频繁改动再说，当然如果你做了，我可以合并
