### ISSUE TITLE
Upload to other cloud drives or file sharing sites.

### ISSUE THREAD

**Issue by My12123** [1439707509/pygui#8]
#3 
trans.7z
drive.google https://drive.google.com/u/2/uc?id=1XeFJMvf_N29BL-zzw2NYC_s27iSw6UIW&export=download&confirm=t&uuid=e1e766a1-ae07-4d64-b24f-066a68512860&at=AKKF8vxgVd-Xy-hm7JWqCOXwKecV:1685525274171
mega https://mega.nz/file/fyp1hIzJ#3JUInG8kxCl1dQgtkuoP70mD_bCbBJxWDVndi0JBOTA
uploadrar https://uploadrar.com/n3zp3ysgllk6

**Comment by 1439707509** [comment]
那个......因为新加了 py3langid 这个第三方库，我又重新打包了，然后想了想，分开放很麻烦，然后直接一起，分卷压缩了，你这个已经没用了
